---
title: "Data Science for Public Policy"
subtitle: "Final Project: Predicting the PMJDY Takeup Rate in India"
author: "Meenakshi Alagusundaram - ma2309, Sanya Bahal - sb2063, Diana Rivas - dnr36, Sona Sarin - srs368"
execute:
  warning: false
format:
  html:
    embed-resources: true
---

# Data Analysis

## Geospatial Analysis

```{r}

# Making a SF to conduct geo-spatial analysis 
sf_pmjdy <- st_as_sf(pmjdy, coords = c("longitude", "latitude")) %>%
  st_set_crs(4326)

# Loading data for the map of India 
india <- geoboundaries(
  country = "India",
  adm_lvl = "adm1",
  type = "simplified"
  )

# Setting crs as the same from sf_pmjdy to ensure spatial join is done correctly 
india <- st_transform(india, crs = st_crs(sf_pmjdy))

# Spatial join 
india_pmjdy <- st_join(india, sf_pmjdy)

# Making a function to make more choropleths 

#' india_choropleth
#'
#' @description This function takes the argument of "indicator" and creates a choropleth for India. This helps to visualize the differences of similarities among the different states over a common indicator. 
#' @param indicator 
#'
#' @return A choropleth map of India with the selected indicator.
#' @export
#'
#' @examples india_choropleth(employment)
#' 
india_choropleth <- function(indicator) {
  
  india_pmjdy %>%
    ggplot() +
    geom_sf(aes(fill = !!sym(indicator)), color = "darkorange2", size = 0.1) +
    scale_fill_gradient(
        low = "white", 
        high = "darkgreen",
    ) +
   labs(title = paste0(as.character(attr(india_pmjdy[[indicator]], "label")), " across India"), 
      fill = attr(india_pmjdy[[indicator]], "label")) +
    theme_void() +
    theme(
      plot.title = element_text(size = 12),
       legend.title = element_text(size = 10) 
    )
   
}

# Variables of interest for PMJDY takeup are education, employment and income: 
choro_pmjdy <- india_choropleth(indicator = "pmjdy")
choro_edu <- india_choropleth(indicator = "educationindex")
choro_emp <- india_choropleth(indicator = "employment")
choro_income <- india_choropleth(indicator = "incomeindex")

choro_pmjdy

choro_edu + choro_emp + choro_income 

```

This geospatial analysis of the state level characteristics helps visualize the correlation between different indicators and the PMJDY take up rate. The first choropleth shows the take-up rates across India and we can see that the highest rates are found in the north east part of the country, in states such as Assam and Chhattisgarh.

Upon further exploration we see that the areas with the highest PMJDY take up are also those with lower educational index, employment rates and income. This correlation suggests that the program was able to successfully target its intended population. A limitation for this finding is that it merely represents a correlation and not a causal link. Further analysis on the data will be conducted to create a model that optimizes accuracy to predict the take up rate based on the indicators explored through this geospatial analysis.\`
