---
title: "Data Science for Public Policy"
subtitle: "Final Project: Predicting the PMJDY Takeup Rate in India"
author: "Meenakshi Alagusundaram - ma2309, Sanya Bahal - sb2063, Diana Rivas - dnr36, Sona Sarin - srs368"
execute:
  warning: false
format:
  html:
    embed-resources: true
---

# Overview  

\
The Pradhan Mantri Jan-Dhan Yojana (PMJDY) is a pivotal initiative by the Government of India aimed at expanding financial inclusion to all households in the country. This national mission targets the inclusion of excluded sections, such as weaker sections and low-income groups, ensuring they have access to essential financial services. These services include basic savings bank accounts, need-based credit, and remittance facilities, along with comprehensive coverage under insurance and pension schemes.

A key feature of PMJDY is its commitment to leveraging cutting-edge technology to overcome barriers like poor connectivity and streamline online transactions. Each account holder is equipped with a RuPay Debit Card, which comes with an inbuilt accident insurance cover of ₹1 lakh, enhancing financial security.

The scheme also focuses on integrating government benefits into the banking system through the Direct Benefits Transfer (DBT) scheme, ensuring subsidies and other aids are directly transferred to beneficiaries' accounts. Additionally, the initiative encourages mobile-based transactions through established telecom networks, further promoting financial inclusivity.

PMJDY also extends its reach to engage the youth of India, inviting them to partake in this comprehensive drive towards nationwide financial inclusion.\

##  Research Focus  

\
Our project investigates how state-specific characteristics can predict the take-up rate of the Pradhan Mantri Jan-Dhan Yojana (PMJDY) across different states. Utilizing a comprehensive dataset that spans multiple years and includes various indicators at the state level, our analysis aims to develop a predictive model. This model will not only forecast the uptake rates of PMJDY but also identify key factors influencing these rates, guiding more effective implementation of financial inclusion policies.\

## Background

According to the G20 report published by Global Partnership in 2023, India had set a target of achieving 80 percent financial inclusion (i.e., 80 percent of its population has access to financial services), which the nation achieved at the country level in 6 years (41 years ahead of the target). To achieve this target, India launched numerous financial inclusion programs at the national level. PMJDY was launched nationwide in 2014 in India. Administered by the Ministry of Finance, this policy seeks to increase financial undefinedinclusion among lower income groups of the Indian society. In doing so, the policy offers an array of financial services, including savings accounts, debit cards, pension, accident and life insurance, access to credit, and programs aiming to increase financial literacy to individuals. Eligible individuals include Indian citizens above 10 years of age. \
\
\
***PMJDY Services***\

Financial services other than a savings account are administered through interaction and coordination with other schemes. Access to credit under PMJDY is facilitated through an overdraft facility, which becomes available to account holders after six months of satisfactory operation of their accounts. This facility aims to provide a financial safety net and promote small-scale entrepreneurship. For pension services, PMJDY links with schemes like the Pradhan Mantri Shram Yogi Maan-Dhan (PMSYM) and the National Pension Scheme (NPS), catering primarily to the unorganized sector. These schemes allow individuals to voluntarily contribute to a pension account during their working life, ensuring financial stability in old age. PMJDY accounts also serve as conduits for beneficiaries to enroll in other government programs, such as accident and life insurance under Pradhan Mantri Suraksha Bima Yojana (PMSBY) and Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY), respectively.

## Literature Review

Literature suggests that PMJDY is likely to be associated with an increase in financial inclusion (Naik et al., 2018; Gupta 2023; Senapati 2018). However, despite this progress, some marginalized groups (e.g., women, lower income groups, lesser educated population) of the population remain underbanked or underserved by the banking sector (Ravi et al., 2019; Barik et al., 2019). 

***Program Participation***

As of the program's nine-year mark (2023), PMJDY included over 500 million people in the formal banking system (Jayaswal, 2023). Notably, about 67 percent of these accounts were opened in rural and semi-urban areas. Additionally, around 340 million debit cards have been issued, and 2 lakh Indian Rupee (INR) (approximately \$2400 USD) in accident insurance coverage have provided an added layer of financial security. 

The participation rate of PMJDY, as found by our analysis, reveals an increase from an average of 18.8 percent in 2016 to 26.2 percent in 2020. This means that on average, 18.8 percent of the population in each state was participating in the policy as compared to 26.2 percent in 2020, a 7.4 percentage point increase. 

***Challenges Faced by PMJDY*** 

PMJDY, like many social programs, has faced some implementation challenges. One of the primary challenges is managing duplicate and dormant accounts, which can skew estimates of the program's effectiveness and resource allocation. This issue is closely tied to the need for enhancing financial literacy among the beneficiaries, ensuring they understand and utilize the financial services offered effectively (Malik et al., 2023).

While that challenge is valid across geographies, a challenge particularly acute for rural areas is internet connectivity. Inadequate networking and bandwidth issues present hindrances in administering the program smoothly, especially in rural areas. These issues are particularly challenging in areas where banking infrastructure is already limited. The scarcity of ATMs in rural areas is one such barrier. Many beneficiaries are not accustomed to or lack easy access to ATMs and find it challenging to utilize these services effectively. In addition, a notable gender disparity exists within the banking sector, suggesting that women may not be reaping the benefits of the scheme as much as men. This gender gap points to a need for more inclusive financial services.
